/**
 * Regenerates src/data/bukhari-nikah.ts from a saved copy of sunnah.com/bukhari/67.
 * Usage: curl -sL https://sunnah.com/bukhari/67 -o /tmp/bukhari67.html && npx tsx scripts/build-hadith.ts /tmp/bukhari67.html
 */
import { readFileSync, writeFileSync } from "node:fs";

type Entry = {
  reference: string;
  inBook: string;
  chapter: string;
  chapterArabic: string;
  narrator: string;
  english: string;
  arabic: string;
};

const source = readFileSync(process.argv[2] ?? "/tmp/bukhari67.html", "utf8");

function decode(value: string): string {
  return value
    .replace(/<br\s*\/?>/gi, " ")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#039;|&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/[\u200e\u200f]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function lastBefore(pattern: RegExp, index: number): string {
  let found = "";
  for (const match of source.matchAll(pattern)) {
    if (match.index === undefined || match.index >= index) break;
    found = decode(match[1]);
  }
  return found;
}

const starts = [...source.matchAll(/<div class="actualHadithContainer/g)].map((m) => m.index ?? 0);
const entries: Entry[] = [];

for (const [position, at] of starts.entries()) {
  const block = source.slice(at, starts[position + 1] ?? source.length);
  const reference = decode(/<div class="hadith_reference_sticky">([\s\S]*?)<\/div>/.exec(block)?.[1] ?? "");
  const narrator = decode(/<div class=hadith_narrated>([\s\S]*?)<\/div>/.exec(block)?.[1] ?? "");
  const english = decode(/<div class=text_details>([\s\S]*?)<\/div>/.exec(block)?.[1] ?? "");
  const arabic = decode(
    /<div class="arabic_hadith_full arabic">([\s\S]*?)<!-- End hadith -->/.exec(block)?.[1] ?? "",
  ).replace(/\s*\.\s*$/, ".");
  const inBook = decode(
    /In-book reference\s*<\/td>\s*<td[^>]*>([\s\S]*?)<\/td>/.exec(block)?.[1] ?? "",
  ).replace(/^:\s*/, "");
  const chapter = lastBefore(/<div class="?englishchapter"?[^>]*>([\s\S]*?)<\/div>/g, at);
  const chapterArabic = lastBefore(/<div class="?arabicchapter[^>]*>([\s\S]*?)<\/div>/g, at);
  if (!reference || !english) continue;
  entries.push({ reference, inBook, chapter, chapterArabic, narrator, english, arabic });
}

const file = `// Sahih al-Bukhari, Book 67: Wedlock, Marriage (Nikaah).
// Generated by scripts/build-hadith.ts from sunnah.com/bukhari/67. Do not edit by hand.

export type Hadith = {
  reference: string;
  inBook: string;
  chapter: string;
  chapterArabic: string;
  narrator: string;
  english: string;
  arabic: string;
};

export const hadiths: Hadith[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync("src/data/bukhari-nikah.ts", file);
console.log(`wrote ${entries.length} hadiths`);
